Ignore cloned_instead_of_copied clippy lint
The .clippy.toml declares this crate's msrv as 1.31.0, so it is a Clippy
bug that this lint is triggering in the first place. Option::copied is
from Rust 1.35.

https://github.com/rust-lang/rust-clippy/issues/7127

    error: used `cloned` where `copied` could be used instead
       --> src/error.rs:248:14
        |
    248 |             .cloned()
        |              ^^^^^^ help: try: `copied`
        |
        = note: `-D clippy::cloned-instead-of-copied` implied by `-D clippy::pedantic`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied

    error: used `cloned` where `copied` could be used instead
       --> src/error.rs:250:39
        |
    250 |         let end = self.end_span.get().cloned().unwrap_or_else(Span::call_site);
        |                                       ^^^^^^ help: try: `copied`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied

    error: used `cloned` where `copied` could be used instead
       --> src/error.rs:337:14
        |
    337 |             .cloned()
        |              ^^^^^^ help: try: `copied`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied

    error: used `cloned` where `copied` could be used instead
       --> src/error.rs:339:39
        |
    339 |         let end = self.end_span.get().cloned().unwrap_or_else(Span::call_site);
        |                                       ^^^^^^ help: try: `copied`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied