Update internal code generator to rustfmt 2.0.0-rc.2
The previously pinned rustfmt commit + toolchain have no longer been
compiling as of servo/rust-smallvec#248.

    error[E0658]: unions with non-`Copy` fields are unstable
       --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.6.0/src/lib.rs:353:1
        |
    353 | / union SmallVecData<A: Array> {
    354 | |     inline: core::mem::ManuallyDrop<MaybeUninit<A>>,
    355 | |     heap: (*mut A::Item, usize),
    356 | | }
        | |_^
        |
        = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information
        = help: add `#![feature(untagged_unions)]` to the crate attributes to enable