Bump codegen to rustfmt built with nightly-2021-04-26
The previously used rustfmt commit only builds with an old version of
1.52-dev, and that one is missing trait bounds on const fn.

    error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.4/src/mutex.rs:143:6
        |
    143 | impl<R: RawMutex, T> Mutex<R, T> {
        |      ^
        = help: add `#![feature(const_fn)]` to the crate attributes to enable

    error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.4/src/remutex.rs:224:6
        |
    224 | impl<R: RawMutex, G: GetThreadId, T> ReentrantMutex<R, G, T> {
        |      ^
        = help: add `#![feature(const_fn)]` to the crate attributes to enable

    error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.4/src/remutex.rs:224:19
        |
    224 | impl<R: RawMutex, G: GetThreadId, T> ReentrantMutex<R, G, T> {
        |                   ^
        = help: add `#![feature(const_fn)]` to the crate attributes to enable

    error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.4/src/rwlock.rs:348:6
        |
    348 | impl<R: RawRwLock, T> RwLock<R, T> {
        |      ^
        = help: add `#![feature(const_fn)]` to the crate attributes to enable