Ignore let_underscore_drop clippy pedantic lint in test suite
    error: non-binding `let` on a type that implements `Drop`
     --> tests/regression/issue1108.rs:4:5
      |
    4 |     let _ = syn::parse_file(data);
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: `-D clippy::let-underscore-drop` implied by `-D clippy::pedantic`
      = help: consider using an underscore-prefixed named binding or dropping explicitly with `std::mem::drop`
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_drop