Resolve from_iter_instead_of_collect clippy style lint
    error: usage of `FromIterator::from_iter`
        --> src/ty.rs:1012:30
         |
    1012 |                   let tokens = TokenStream::from_iter(args.into_iter().zip(&dot3.spans).map(
         |  ______________________________^
    1013 | |                     |(mut arg, span)| {
    1014 | |                         arg.set_span(*span);
    1015 | |                         arg
    1016 | |                     },
    1017 | |                 ));
         | |__________________^
         |
         = note: `-D clippy::from-iter-instead-of-collect` implied by `-D clippy::all`
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect
    help: use `.collect()` instead of `::from_iter()`
         |
    1012 |                 let tokens = args.into_iter().zip(&dot3.spans).map(
    1013 |                     |(mut arg, span)| {
    1014 |                         arg.set_span(*span);
    1015 |                         arg
    1016 |                     },
    1017 |                 ).collect::<TokenStream<_>>();
         |